return {
  -- -- Add the nvim-ts-context-commentstring plugin
  -- {
  --   "JoosepAlviste/nvim-ts-context-commentstring",
  --   dependencies = { "nvim-treesitter/nvim-treesitter" },
  --   config = function()
  --     -- Configure Treesitter for context-aware commenting
  --     require("nvim-treesitter.configs").setup({
  --       context_commentstring = {
  --         enable = true,
  --         enable_autocmd = false, -- Manual triggering for performance
  --       },
  --     })
  --   end,
  -- },
  -- -- Ensure Comment.nvim is configured to use nvim-ts-context-commentstring
  -- {
  --   "numToStr/Comment.nvim",
  --   config = function()
  --     require("Comment").setup({
  --       pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
  --     })
  --   end,
  -- },
}
